### ISSUE TITLE
It's too easy to miss queues

### ISSUE THREAD

**Issue by MatthewRichards** [garethed/Q3#30]
PoolQ2 is very configurable, and one of the things you can configure is how long the popups stay open for. Get it right and you're safe against lunch being served while you happen to be looking in the other direction. Q3 doesn't do this - if you're not staring at the screen for the relevant 5 second period, you don't get notified. This is happening to me quite a lot... What can we do about it?

Note that this applies both to the queues originally popping up, and to the notification when the queue is started.

**Comment by garethed** [comment]
Need:
- persist Q started notifications until you dismiss them always
- option to do the same for new Q notifications
- when reconnecting, show notifications for new Qs
